var struct_z___construct___u_function___u_advanced_sessions_library___add_or_modify_extra_settings___statics =
[
    [ "AdvancedSessionsLibrary_eventAddOrModifyExtraSettings_Parms", "struct_z___construct___u_function___u_advanced_sessions_library___add_or_modify_extra_settings__45caef3bbd86a4c99f1f2450e2925464.html", null ]
];