var struct_z___construct___u_function___a_player_controller_realms_forge___set_selected_buildable___statics =
[
    [ "PlayerControllerRealmsForge_eventSetSelectedBuildable_Parms", "struct_z___construct___u_function___a_player_controller_realms_forge___set_selected_buildable___842e9d5b7fbacf1bb73cf3e6ec32811f.html", null ]
];